name: deploy

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: "tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Switch to third-party repository"
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: 1488darkStalker228
          repo: page-factory-tests
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: tests.yml
          ref: master